const mongoose = require('mongoose');
const { connectDB, User, Video, Comment, Report } = require('./db');
require('dotenv').config();

const seedData = async () => {
  try {
    await connectDB();
    console.log('Seeding initial MongoDB data with Multi-Category Ranked Global Showcase...');

    // Clear existing data
    await User.deleteMany();
    await Video.deleteMany();
    await Comment.deleteMany();
    await Report.deleteMany();
    
    // Seed Users & Creator Channels
    const users = [
      { 
        id: '1', 
        username: 'free_user', 
        name: 'Free User', 
        email: 'free@example.com', 
        plan: 'free', 
        theme: null,
        banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=free_user',
        bio: 'Tech enthusiast & video explorer.',
        country: 'United States',
        countryCode: 'US',
        countryFlag: '🇺🇸',
        subscribers: [
          { userId: '2', username: 'bronze_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bronze_user', date: new Date(Date.now() - 86400000 * 5) }
        ],
        subscriptions: ['Blender Foundation', 'Red Bull Extreme Hub', 'Taste of Tokyo'],
        known_devices: [], 
        downloads: [] 
      },
      { 
        id: '2', 
        username: 'bronze_user', 
        name: 'Bronze User', 
        email: 'bronze@example.com', 
        plan: 'bronze', 
        theme: null,
        banner: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bronze_user',
        bio: 'Animation lover & 3D render artist.',
        country: 'Canada',
        countryCode: 'CA',
        countryFlag: '🇨🇦',
        subscribers: [],
        subscriptions: ['Blender Foundation', 'Tokyo Digital FX Lab'],
        known_devices: [], 
        downloads: [] 
      },
      // --- GLOBAL CREATORS BY CATEGORY ---
      // 1. Entertainment & Animation
      {
        id: 'ch_blender',
        username: 'Blender Foundation',
        name: 'Blender Foundation',
        email: 'blender@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Blender',
        bio: 'Official Open Source 3D Animation & VFX Studio based in Amsterdam, Netherlands.',
        country: 'Netherlands',
        countryCode: 'NL',
        countryFlag: '🇳🇱',
        creatorBadges: ['👑 #1 in Entertainment', '🏆 3D Legend', '⭐ 15M+ Views Club'],
        globalCreatorRank: 1,
        featuredScore: 99.8,
        subscribers: [
          { userId: '1', username: 'free_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=free_user' },
          { userId: '2', username: 'bronze_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bronze_user' }
        ]
      },
      {
        id: 'ch_tokyo_fx',
        username: 'Tokyo Digital FX Lab',
        name: 'Tokyo Digital FX Lab',
        email: 'tokyofx@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TokyoFX',
        bio: 'Next-generation Unreal Engine 5 cinematics and Cyberpunk CGI studio from Tokyo, Japan.',
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        creatorBadges: ['🥈 #2 in Entertainment', '⚡ Unreal Master', '🔥 14M+ Views'],
        globalCreatorRank: 2,
        featuredScore: 98.9,
        subscribers: [
          { userId: '1', username: 'free_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=free_user' }
        ]
      },
      {
        id: 'ch_sintel',
        username: 'Sintel Open Cinema',
        name: 'Sintel Open Cinema',
        email: 'sintel@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SintelStudio',
        bio: 'Legendary open-movie production studio behind award-winning fantasy animations.',
        country: 'Netherlands',
        countryCode: 'NL',
        countryFlag: '🇳🇱',
        creatorBadges: ['🥉 #3 in Entertainment', '🐉 Fantasy Masterpiece'],
        globalCreatorRank: 3,
        featuredScore: 97.5,
        subscribers: []
      },
      // 2. Sports Creators
      {
        id: 'ch_redbull',
        username: 'Red Bull Extreme Hub',
        name: 'Red Bull Extreme Hub',
        email: 'redbull@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RedBullExtreme',
        bio: 'The undisputed home of world-record stunts, stratosphere skydiving, and extreme action sports.',
        country: 'Austria',
        countryCode: 'AT',
        countryFlag: '🇦🇹',
        creatorBadges: ['👑 #1 in Sports', '🚀 Stratosphere Record', '🔥 18M+ Views'],
        globalCreatorRank: 4,
        featuredScore: 99.9,
        subscribers: [
          { userId: '1', username: 'free_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=free_user' }
        ]
      },
      {
        id: 'ch_f1_apex',
        username: 'F1 World Apex',
        name: 'F1 World Apex',
        email: 'f1apex@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=F1Apex',
        bio: 'Formula 1 high-speed telemetry, onboard 4K cameras, and legendary street circuit analysis.',
        country: 'Monaco',
        countryCode: 'MC',
        countryFlag: '🇲🇨',
        creatorBadges: ['🥈 #2 in Sports', '🏎️ 350 km/h Apex', '🏆 Monaco GP Winner'],
        globalCreatorRank: 5,
        featuredScore: 98.2,
        subscribers: []
      },
      {
        id: 'ch_wsl_waves',
        username: 'WSL Wave Masters',
        name: 'WSL Wave Masters',
        email: 'waves@example.com',
        plan: 'silver',
        banner: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WSLWaves',
        bio: 'Chasing the largest swells on planet Earth, from Nazaré Portugal to Teahupoo Tahiti.',
        country: 'Portugal',
        countryCode: 'PT',
        countryFlag: '🇵🇹',
        creatorBadges: ['🥉 #3 in Sports', '🌊 80ft Nazaré Giant'],
        globalCreatorRank: 6,
        featuredScore: 96.5,
        subscribers: []
      },
      // 3. Food & Culinary Creators
      {
        id: 'ch_taste_tokyo',
        username: 'Taste of Tokyo',
        name: 'Taste of Tokyo',
        email: 'tokyofood@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TasteOfTokyo',
        bio: 'Michelin-starred Japanese masters, centuries-old recipes, and Tokyo midnight ramen traditions.',
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        creatorBadges: ['👑 #1 in Food', '🍜 3-Star Michelin', '⭐ 16M+ Views'],
        globalCreatorRank: 7,
        featuredScore: 99.7,
        subscribers: [
          { userId: '1', username: 'free_user', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=free_user' }
        ]
      },
      {
        id: 'ch_napoli_eats',
        username: 'Napoli Authentic Eats',
        name: 'Napoli Authentic Eats',
        email: 'napoli@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NapoliEats',
        bio: 'Real Neapolitan pizza art, high-hydration dough fermentation, and Italian culinary traditions.',
        country: 'Italy',
        countryCode: 'IT',
        countryFlag: '🇮🇹',
        creatorBadges: ['🥈 #2 in Food', '🍕 Woodfired Master', '🇮🇹 Italian Heritage'],
        globalCreatorRank: 8,
        featuredScore: 97.8,
        subscribers: []
      },
      {
        id: 'ch_chef_gourmet',
        username: 'Le Chef Gourmet',
        name: 'Le Chef Gourmet',
        email: 'gourmet@example.com',
        plan: 'silver',
        banner: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChefGourmet',
        bio: 'Parisian fine dining, master pastry arts, and 100-layer croissant techniques.',
        country: 'France',
        countryCode: 'FR',
        countryFlag: '🇫🇷',
        creatorBadges: ['🥉 #3 in Food', '🥐 100-Layer Croissant'],
        globalCreatorRank: 9,
        featuredScore: 95.9,
        subscribers: []
      },
      // 4. Gaming Creators
      {
        id: 'ch_epic_gametech',
        username: 'Epic GameTech Hub',
        name: 'Epic GameTech Hub',
        email: 'gametech@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=EpicGameTech',
        bio: 'Cutting-edge Unreal Engine tech demos, next-gen photoreal gameplay, and gaming physics.',
        country: 'United States',
        countryCode: 'US',
        countryFlag: '🇺🇸',
        creatorBadges: ['👑 #1 in Gaming', '🎮 Next-Gen Graphics', '🔥 15M+ Views'],
        globalCreatorRank: 10,
        featuredScore: 99.4,
        subscribers: []
      },
      {
        id: 'ch_pro_esports',
        username: 'Pro Esports Arena',
        name: 'Pro Esports Arena',
        email: 'esports@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProEsports',
        bio: 'World championship finals, clutch highlight reels, and Korean esports dominance.',
        country: 'South Korea',
        countryCode: 'KR',
        countryFlag: '🇰🇷',
        creatorBadges: ['🥈 #2 in Gaming', '🏆 1v5 World Finals Ace'],
        globalCreatorRank: 11,
        featuredScore: 97.2,
        subscribers: []
      },
      // 5. Tech & Science
      {
        id: 'ch_silicon_robotics',
        username: 'Silicon Robotics Lab',
        name: 'Silicon Robotics Lab',
        email: 'robotics@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SiliconRobotics',
        bio: 'Humanoid AI robotics, neural locomotion networks, and the future of autonomous systems.',
        country: 'United States',
        countryCode: 'US',
        countryFlag: '🇺🇸',
        creatorBadges: ['👑 #1 in Tech', '🤖 Humanoid AI', '⚡ 13M+ Views'],
        globalCreatorRank: 12,
        featuredScore: 99.1,
        subscribers: []
      },
      {
        id: 'ch_quantum_science',
        username: 'Quantum Science World',
        name: 'Quantum Science World',
        email: 'quantum@example.com',
        plan: 'silver',
        banner: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=QuantumScience',
        bio: 'Demystifying quantum mechanics, superconducting qubits, and astrophysics discoveries.',
        country: 'United Kingdom',
        countryCode: 'GB',
        countryFlag: '🇬🇧',
        creatorBadges: ['🥈 #2 in Tech', '⚛️ Qubit Breakthrough'],
        globalCreatorRank: 13,
        featuredScore: 96.4,
        subscribers: []
      },
      // 6. Music & Visual Arts
      {
        id: 'ch_tokyo_synth',
        username: 'Tokyo Soundwave',
        name: 'Tokyo Soundwave',
        email: 'soundwave@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TokyoSoundwave',
        bio: 'Immersive synthwave audiovisual concerts, neon aesthetics, and Tokyo electronic music.',
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        creatorBadges: ['👑 #1 in Music', '🎹 Cyber Synthwave', '⭐ 11M+ Views'],
        globalCreatorRank: 14,
        featuredScore: 98.0,
        subscribers: []
      },
      {
        id: 'ch_london_symphony',
        username: 'London Symphony Visuals',
        name: 'London Symphony Visuals',
        email: 'londonsymphony@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LondonSymphony',
        bio: 'Cinematic orchestral performances recorded with 8K spatial acoustics in Royal Albert Hall.',
        country: 'United Kingdom',
        countryCode: 'GB',
        countryFlag: '🇬🇧',
        creatorBadges: ['🥈 #2 in Music', '🎻 Interstellar Orchestral'],
        globalCreatorRank: 15,
        featuredScore: 97.1,
        subscribers: []
      },
      // 7. Travel & Nature 8K
      {
        id: 'ch_nordic_aurora',
        username: 'Nordic Aurora Cinema',
        name: 'Nordic Aurora Cinema',
        email: 'nordic@example.com',
        plan: 'gold',
        banner: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NordicCinema',
        bio: 'Ultra-high-definition 8K cinematics capturing Arctic Glaciers, Northern Lights, and Fjords.',
        country: 'Norway',
        countryCode: 'NO',
        countryFlag: '🇳🇴',
        creatorBadges: ['👑 #1 in Nature', '❄️ 8K Aurora Cinema', '🏆 World Drone Award'],
        globalCreatorRank: 16,
        featuredScore: 98.7,
        subscribers: []
      },
      {
        id: 'ch_alpine_cinema',
        username: 'Alpine High Cinema',
        name: 'Alpine High Cinema',
        email: 'alpine@example.com',
        plan: 'silver',
        banner: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1600&auto=format&fit=crop&q=80',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlpineCinema',
        bio: 'Aerial 8K FPV flights through the Swiss Alps, Mont Blanc, and Matterhorn peaks.',
        country: 'Switzerland',
        countryCode: 'CH',
        countryFlag: '🇨🇭',
        creatorBadges: ['🥈 #2 in Nature', '🏔️ Matterhorn 8K FPV'],
        globalCreatorRank: 17,
        featuredScore: 96.9,
        subscribers: []
      }
    ];

    await User.insertMany(users);
    console.log(`Inserted ${users.length} Users with Categories & Creators.`);

    // --- SEED VIDEOS WITH CATEGORY-SPECIFIC RANKS ---
    const sampleVideos = [
      // === 1. SPORTS & EXTREME ACTION ===
      {
        id: 'v_sports_1',
        title: 'Red Bull Stratos: Record Space Jump & 843 MPH Supersonic Freefall',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=800&auto=format&fit=crop&q=80',
        channel: 'Red Bull Extreme Hub',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RedBullExtreme',
        views: '18.2M views',
        viewsCount: 18200000,
        timestamp: '1 week ago',
        description: 'Watch Felix Baumgartner step into the void from 128,100 feet in the stratosphere, breaking the sound barrier in historic 4K telemetry.',
        tags: ['sports', 'redbull', 'extreme', 'space jump', 'speed', 'supersonic'],
        likesCount: 940000,
        country: 'Austria',
        countryCode: 'AT',
        countryFlag: '🇦🇹',
        region: 'europe',
        category: 'Sports',
        categoryRank: 1,
        categoryIcon: '⚽',
        isFeatured: true,
        globalRank: 1,
        featuredBadge: '🏆 #1 Worldwide in Sports',
        performanceScore: 99.9,
        duration: '09:30'
      },
      {
        id: 'v_sports_2',
        title: 'Monaco Grand Prix: 4K 60FPS Onboard Flying Lap Masterclass',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
        channel: 'F1 World Apex',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=F1Apex',
        views: '12.4M views',
        viewsCount: 12400000,
        timestamp: '3 days ago',
        description: 'Millimeter-perfect apex precision through the Casino Square and Swimming Pool chicane at 290 km/h in Monte Carlo.',
        tags: ['sports', 'f1', 'monaco', 'racing', 'apex', 'motorsport'],
        likesCount: 680000,
        country: 'Monaco',
        countryCode: 'MC',
        countryFlag: '🇲🇨',
        region: 'europe',
        category: 'Sports',
        categoryRank: 2,
        categoryIcon: '⚽',
        isFeatured: true,
        globalRank: 7,
        featuredBadge: '🥈 #2 Worldwide in Sports',
        performanceScore: 98.2,
        duration: '04:15'
      },
      {
        id: 'v_sports_3',
        title: 'Riding the 80-Foot Giant: World Record Big Wave Surfing at Nazaré',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop&q=80',
        channel: 'WSL Wave Masters',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WSLWaves',
        views: '9.8M views',
        viewsCount: 9800000,
        timestamp: '5 days ago',
        description: 'Towing into towering 80ft walls of moving ocean water under the historic lighthouse of Praia do Norte, Portugal.',
        tags: ['sports', 'surfing', 'nazare', 'ocean', 'big wave', 'portugal'],
        likesCount: 520000,
        country: 'Portugal',
        countryCode: 'PT',
        countryFlag: '🇵🇹',
        region: 'europe',
        category: 'Sports',
        categoryRank: 3,
        categoryIcon: '⚽',
        isFeatured: true,
        globalRank: 12,
        featuredBadge: '🥉 #3 Worldwide in Sports',
        performanceScore: 96.5,
        duration: '07:45'
      },

      // === 2. FOOD & CULINARY ARTS ===
      {
        id: 'v_food_1',
        title: 'Tokyo 3-Star Michelin Master: 50 Years of Handcrafted Soba & Dashi Art',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
        channel: 'Taste of Tokyo',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TasteOfTokyo',
        views: '16.9M views',
        viewsCount: 16900000,
        timestamp: '4 days ago',
        description: 'Step into the legendary Ginza kitchen of 82-year-old Master Chef Kenji Takahashi as he mills buckwheat into culinary perfection.',
        tags: ['food', 'tokyo', 'michelin', 'culinary', 'japan', 'gourmet'],
        likesCount: 880000,
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        region: 'asia_pacific',
        category: 'Food & Culinary',
        categoryRank: 1,
        categoryIcon: '🍔',
        isFeatured: true,
        globalRank: 2,
        featuredBadge: '🏆 #1 Worldwide in Food & Culinary',
        performanceScore: 99.7,
        duration: '14:20'
      },
      {
        id: 'v_food_2',
        title: 'The 72-Hour Dough: Secrets of Authentic Woodfired Neapolitan Pizza',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
        channel: 'Napoli Authentic Eats',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NapoliEats',
        views: '11.5M views',
        viewsCount: 11500000,
        timestamp: '6 days ago',
        description: 'San Marzano tomatoes, fresh Buffalo Mozzarella, and 900°F volcanic stone baking in the heart of Naples, Italy.',
        tags: ['food', 'pizza', 'italy', 'napoli', 'artisan', 'baking'],
        likesCount: 610000,
        country: 'Italy',
        countryCode: 'IT',
        countryFlag: '🇮🇹',
        region: 'europe',
        category: 'Food & Culinary',
        categoryRank: 2,
        categoryIcon: '🍔',
        isFeatured: true,
        globalRank: 8,
        featuredBadge: '🥈 #2 Worldwide in Food & Culinary',
        performanceScore: 97.8,
        duration: '11:10'
      },
      {
        id: 'v_food_3',
        title: 'Mastering the 100-Layer Croissant: French Haute Pâtisserie Technique',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
        channel: 'Le Chef Gourmet',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChefGourmet',
        views: '8.9M views',
        viewsCount: 8900000,
        timestamp: '1 week ago',
        description: 'Normandy butter lamination, precise temperature fermentation, and creating the ultimate honeycomb interior pastry structure.',
        tags: ['food', 'pastry', 'croissant', 'france', 'paris', 'bakery'],
        likesCount: 470000,
        country: 'France',
        countryCode: 'FR',
        countryFlag: '🇫🇷',
        region: 'europe',
        category: 'Food & Culinary',
        categoryRank: 3,
        categoryIcon: '🍔',
        isFeatured: true,
        globalRank: 13,
        featuredBadge: '🥉 #3 Worldwide in Food & Culinary',
        performanceScore: 95.9,
        duration: '08:50'
      },

      // === 3. ENTERTAINMENT & CGI ANIMATION ===
      {
        id: 'v_ent_1',
        title: 'Big Buck Bunny (4K Ultra HD Remaster) - World Open Movie Classic',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
        channel: 'Blender Foundation',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Blender',
        views: '15.4M views',
        viewsCount: 15400000,
        timestamp: '2 days ago',
        description: 'The award-winning 3D open-source cinema masterpiece created in Amsterdam, remastered with next-generation 4K 60FPS ray tracing.',
        tags: ['entertainment', '3d animation', 'blender', 'open movie', 'cgi', '4k'],
        likesCount: 890000,
        country: 'Netherlands',
        countryCode: 'NL',
        countryFlag: '🇳🇱',
        region: 'europe',
        category: 'Entertainment',
        categoryRank: 1,
        categoryIcon: '🎬',
        isFeatured: true,
        globalRank: 3,
        featuredBadge: '🏆 #1 Worldwide in Entertainment',
        performanceScore: 99.8,
        duration: '09:56'
      },
      {
        id: 'v_ent_2',
        title: 'Neon Odyssey: Cyberpunk Neo-Tokyo in Unreal Engine 5.5 (8K Cinematics)',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80',
        channel: 'Tokyo Digital FX Lab',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TokyoFX',
        views: '14.1M views',
        viewsCount: 14100000,
        timestamp: '4 days ago',
        description: 'Immerse into photorealistic Neo-Tokyo with Lumen global illumination, Nanite geometry, and volumetric rainfall simulations.',
        tags: ['entertainment', 'vfx', 'unreal engine', 'cyberpunk', 'tokyo', 'cgi'],
        likesCount: 750000,
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        region: 'asia_pacific',
        category: 'Entertainment',
        categoryRank: 2,
        categoryIcon: '🎬',
        isFeatured: true,
        globalRank: 4,
        featuredBadge: '🥈 #2 Worldwide in Entertainment',
        performanceScore: 98.9,
        duration: '10:53'
      },
      {
        id: 'v_ent_3',
        title: 'Sintel - The Legendary Dragon Fantasy Movie (Official 4K Master)',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
        channel: 'Sintel Open Cinema',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SintelStudio',
        views: '12.8M views',
        viewsCount: 12800000,
        timestamp: '1 week ago',
        description: 'Follow young Sintel on an epic quest across desert mountains in search of Scales, her pet dragon.',
        tags: ['entertainment', 'fantasy', 'dragon', 'sintel', 'cinema', 'animation'],
        likesCount: 670000,
        country: 'Netherlands',
        countryCode: 'NL',
        countryFlag: '🇳🇱',
        region: 'europe',
        category: 'Entertainment',
        categoryRank: 3,
        categoryIcon: '🎬',
        isFeatured: true,
        globalRank: 6,
        featuredBadge: '🥉 #3 Worldwide in Entertainment',
        performanceScore: 97.5,
        duration: '14:48'
      },

      // === 4. GAMING & ESPORTS ===
      {
        id: 'v_game_1',
        title: 'Unreal Engine 6 Next-Gen Graphics Reveal: Real-Time Photoreal Tech Demo',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
        channel: 'Epic GameTech Hub',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=EpicGameTech',
        views: '15.1M views',
        viewsCount: 15100000,
        timestamp: '2 days ago',
        description: 'Full real-time playable showcase featuring sub-surface skin scattering, dynamic neural weather, and 8K mesh streaming.',
        tags: ['gaming', 'unreal engine', 'tech demo', 'next gen', 'graphics', 'esports'],
        likesCount: 820000,
        country: 'United States',
        countryCode: 'US',
        countryFlag: '🇺🇸',
        region: 'north_america',
        category: 'Gaming',
        categoryRank: 1,
        categoryIcon: '🎮',
        isFeatured: true,
        globalRank: 5,
        featuredBadge: '🏆 #1 Worldwide in Gaming',
        performanceScore: 99.4,
        duration: '12:30'
      },
      {
        id: 'v_game_2',
        title: 'World Championship Finals: The Impossible 1v5 Clutch Ace (4K 120FPS)',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80',
        channel: 'Pro Esports Arena',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ProEsports',
        views: '10.9M views',
        viewsCount: 10900000,
        timestamp: '4 days ago',
        description: 'The single most clutch round in competitive tournament history in front of a sold-out 40,000 fan stadium in Seoul.',
        tags: ['gaming', 'esports', 'clutch', 'championship', 'ace', 'tournament'],
        likesCount: 590000,
        country: 'South Korea',
        countryCode: 'KR',
        countryFlag: '🇰🇷',
        region: 'asia_pacific',
        category: 'Gaming',
        categoryRank: 2,
        categoryIcon: '🎮',
        isFeatured: true,
        globalRank: 9,
        featuredBadge: '🥈 #2 Worldwide in Gaming',
        performanceScore: 97.2,
        duration: '06:20'
      },

      // === 5. TECH & SCIENCE AI ===
      {
        id: 'v_tech_1',
        title: 'Next-Gen Humanoid AI Robotics: Full Autonomous Dexterity & Vision Breakthrough',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
        channel: 'Silicon Robotics Lab',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SiliconRobotics',
        views: '13.7M views',
        viewsCount: 13700000,
        timestamp: '3 days ago',
        description: 'Watch end-to-end neural network models operate bi-pedal balance and fine mechanical manipulation in unstructured environments.',
        tags: ['tech', 'ai', 'robotics', 'humanoid', 'science', 'future'],
        likesCount: 710000,
        country: 'United States',
        countryCode: 'US',
        countryFlag: '🇺🇸',
        region: 'north_america',
        category: 'Tech & Science',
        categoryRank: 1,
        categoryIcon: '💻',
        isFeatured: true,
        globalRank: 10,
        featuredBadge: '🏆 #1 Worldwide in Tech & Science',
        performanceScore: 99.1,
        duration: '15:00'
      },
      {
        id: 'v_tech_2',
        title: 'Quantum Supremacy Decoded: How 1,000 Qubit Processors Change Everything',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&auto=format&fit=crop&q=80',
        channel: 'Quantum Science World',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=QuantumScience',
        views: '9.2M views',
        viewsCount: 9200000,
        timestamp: '5 days ago',
        description: 'Deep dive into cryo-chamber diluters, quantum superposition algorithms, and cryptographic implications.',
        tags: ['tech', 'quantum', 'physics', 'science', 'computing', 'future'],
        likesCount: 490000,
        country: 'United Kingdom',
        countryCode: 'GB',
        countryFlag: '🇬🇧',
        region: 'europe',
        category: 'Tech & Science',
        categoryRank: 2,
        categoryIcon: '💻',
        isFeatured: true,
        globalRank: 14,
        featuredBadge: '🥈 #2 Worldwide in Tech & Science',
        performanceScore: 96.4,
        duration: '16:45'
      },

      // === 6. MUSIC & VISUAL ARTS ===
      {
        id: 'v_music_1',
        title: 'Tokyo Cyber Synthwave Symphony: 4K 60FPS Audiovisual Live Session',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
        channel: 'Tokyo Soundwave',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TokyoSoundwave',
        views: '11.8M views',
        viewsCount: 11800000,
        timestamp: '3 days ago',
        description: 'Immerse into retro-futuristic analog synthesizers and reactive neon laser installations recorded in Shinjuku.',
        tags: ['music', 'synthwave', 'tokyo', 'audiovisual', 'neon', 'concert'],
        likesCount: 640000,
        country: 'Japan',
        countryCode: 'JP',
        countryFlag: '🇯🇵',
        region: 'asia_pacific',
        category: 'Music & Arts',
        categoryRank: 1,
        categoryIcon: '🎵',
        isFeatured: true,
        globalRank: 11,
        featuredBadge: '🏆 #1 Worldwide in Music & Arts',
        performanceScore: 98.0,
        duration: '22:15'
      },
      {
        id: 'v_music_2',
        title: 'London Symphony: Hans Zimmer Interstellar Live at Royal Albert Hall',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&auto=format&fit=crop&q=80',
        channel: 'London Symphony Visuals',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LondonSymphony',
        views: '10.5M views',
        viewsCount: 10500000,
        timestamp: '1 week ago',
        description: '100-piece orchestra and pipe organ performing the iconic sci-fi score with spatial Dolby Atmos sound.',
        tags: ['music', 'orchestra', 'interstellar', 'hans zimmer', 'london', 'symphony'],
        likesCount: 580000,
        country: 'United Kingdom',
        countryCode: 'GB',
        countryFlag: '🇬🇧',
        region: 'europe',
        category: 'Music & Arts',
        categoryRank: 2,
        categoryIcon: '🎵',
        isFeatured: true,
        globalRank: 15,
        featuredBadge: '🥈 #2 Worldwide in Music & Arts',
        performanceScore: 97.1,
        duration: '18:40'
      },

      // === 7. TRAVEL & NATURE 8K ===
      {
        id: 'v_nature_1',
        title: 'Nordic Wonders: 8K Aurora Borealis & Arctic Glaciers Over Norway Fjords',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&auto=format&fit=crop&q=80',
        channel: 'Nordic Aurora Cinema',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NordicCinema',
        views: '12.2M views',
        viewsCount: 12200000,
        timestamp: '5 days ago',
        description: 'Captured with medium-format cinema sensors during winter solar storms over Tromsø and the Lofoten Islands.',
        tags: ['nature', 'travel', '8k', 'aurora', 'norway', 'glaciers'],
        likesCount: 660000,
        country: 'Norway',
        countryCode: 'NO',
        countryFlag: '🇳🇴',
        region: 'europe',
        category: 'Travel & Nature',
        categoryRank: 1,
        categoryIcon: '🏔️',
        isFeatured: true,
        globalRank: 16,
        featuredBadge: '🏆 #1 Worldwide in Travel & Nature',
        performanceScore: 98.7,
        duration: '15:20'
      },
      {
        id: 'v_nature_2',
        title: 'Swiss Alps 8K Drone Symphony: Matterhorn to Jungfrau Mountain Peaks',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
        channel: 'Alpine High Cinema',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AlpineCinema',
        views: '9.6M views',
        viewsCount: 9600000,
        timestamp: '6 days ago',
        description: 'Sweeping high-altitude aerials across snow-capped Swiss mountain ridges and alpine turquoise lakes.',
        tags: ['nature', 'travel', 'swiss alps', '8k', 'matterhorn', 'switzerland'],
        likesCount: 510000,
        country: 'Switzerland',
        countryCode: 'CH',
        countryFlag: '🇨🇭',
        region: 'europe',
        category: 'Travel & Nature',
        categoryRank: 2,
        categoryIcon: '🏔️',
        isFeatured: true,
        globalRank: 17,
        featuredBadge: '🥈 #2 Worldwide in Travel & Nature',
        performanceScore: 96.9,
        duration: '12:00'
      },
      // === 8. SHORTS ===
      {
        id: 'v_short_1',
        title: 'Amazing 3D Illusion! 🤯',
        url: 'https://media.w3.org/2010/05/sintel/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&h=700&auto=format&fit=crop&q=80',
        channel: 'Blender Foundation',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Blender',
        views: '5.2M views',
        viewsCount: 5200000,
        timestamp: '1 day ago',
        description: 'Testing the new geometry nodes in Blender! #blender #3d #animation',
        tags: ['shorts', '3d', 'blender', 'animation'],
        likesCount: 300000,
        country: 'Netherlands',
        countryCode: 'NL',
        countryFlag: '🇳🇱',
        region: 'europe',
        category: 'Entertainment',
        categoryRank: 4,
        categoryIcon: '🎬',
        isFeatured: false,
        globalRank: 50,
        performanceScore: 85.0,
        duration: '0:59',
        isShort: true
      },
      {
        id: 'v_short_2',
        title: 'The Perfect Croissant Hack! 🥐',
        url: 'https://media.w3.org/2010/05/bunny/trailer.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=700&auto=format&fit=crop&q=80',
        channel: 'Le Chef Gourmet',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChefGourmet',
        views: '12M views',
        viewsCount: 12000000,
        timestamp: '2 days ago',
        description: 'How to get perfect honeycomb structure every time. #baking #croissant #food',
        tags: ['shorts', 'baking', 'food', 'pastry'],
        likesCount: 950000,
        country: 'France',
        countryCode: 'FR',
        countryFlag: '🇫🇷',
        region: 'europe',
        category: 'Food & Culinary',
        categoryRank: 4,
        categoryIcon: '🍔',
        isFeatured: false,
        globalRank: 51,
        performanceScore: 92.0,
        duration: '0:45',
        isShort: true
      },
      {
        id: 'v_short_3',
        title: 'F1 Pit Stop in 1.8 seconds! 🏎️💨',
        url: 'https://media.w3.org/2010/05/video/movie_300.mp4',
        thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400&h=700&auto=format&fit=crop&q=80',
        channel: 'F1 World Apex',
        channel_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=F1Apex',
        views: '8.4M views',
        viewsCount: 8400000,
        timestamp: '1 week ago',
        description: 'Blink and you miss it. #f1 #racing #pitstop',
        tags: ['shorts', 'f1', 'sports', 'racing'],
        likesCount: 420000,
        country: 'Monaco',
        countryCode: 'MC',
        countryFlag: '🇲🇨',
        region: 'europe',
        category: 'Sports',
        categoryRank: 4,
        categoryIcon: '⚽',
        isFeatured: false,
        globalRank: 52,
        performanceScore: 88.5,
        duration: '0:15',
        isShort: true
      }
    ];

    await Video.insertMany(sampleVideos);
    console.log(`Inserted ${sampleVideos.length} Multi-Category Ranked Videos into MongoDB.`);

    // Seed Comments
    const comments = [
      {
        id: 'c1',
        video_id: 'v_sports_1',
        username: 'bronze_user',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bronze_user',
        text: 'The view of Earth from the edge of space gives me chills every time. Pure courage!',
        timestamp: '2 hours ago',
        created_at: Date.now() - 7200000,
        likes: 124,
        dislikes: 0,
        location: 'Canada',
        show_location: true
      },
      {
        id: 'c2',
        video_id: 'v_food_1',
        username: 'silver_user',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=silver_user',
        text: 'The dedication and precision in Japanese craftsmanship is truly unbeatable.',
        timestamp: '5 hours ago',
        created_at: Date.now() - 18000000,
        likes: 89,
        dislikes: 0,
        location: 'United Kingdom',
        show_location: true
      }
    ];

    await Comment.insertMany(comments);
    console.log(`Inserted ${comments.length} Comments into MongoDB.`);

    // Seed Sample Historical Reports
    const sampleReports = [
      {
        id: 'rep_101',
        reporterId: '1',
        reporterName: 'Free User',
        targetType: 'video',
        targetId: 'v_sports_1',
        targetTitle: 'Red Bull Extreme Wingsuit Flight Across the Alps',
        targetThumbnail: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop&q=80',
        targetChannel: 'Red Bull Extreme Hub',
        reason: 'Violent or Dangerous Content',
        details: 'Contains extreme stunt jumps near jagged cliff edges without safety warnings.',
        status: 'Action Taken',
        statusNote: 'Our moderation team reviewed this video and added an Age Restriction & Viewer Discretion disclaimer in compliance with Community Guidelines.',
        reportedAt: new Date(Date.now() - 86400000 * 4),
        resolvedAt: new Date(Date.now() - 86400000 * 2)
      },
      {
        id: 'rep_102',
        reporterId: '1',
        reporterName: 'Free User',
        targetType: 'comment',
        targetId: 'c_spam_99',
        targetTitle: 'Click here for free bitcoin and 1000x crypto giveaway telegram link!!',
        targetThumbnail: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bot99',
        targetChannel: 'Blender Foundation',
        reason: 'Spam, Scams or Commercial Solicitation',
        details: 'Automated crypto scam bot spamming suspicious external links under videos.',
        status: 'Resolved',
        statusNote: 'The reported comment violated our anti-spam policy and has been permanently removed. The associated account was penalized.',
        reportedAt: new Date(Date.now() - 86400000 * 2),
        resolvedAt: new Date(Date.now() - 86400000 * 1)
      },
      {
        id: 'rep_103',
        reporterId: '1',
        reporterName: 'Free User',
        targetType: 'video',
        targetId: 'v_tech_1',
        targetTitle: 'Autonomous AI Robotics: Atlas Gen-4 World Demonstration',
        targetThumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
        targetChannel: 'CyberTech Dynamics',
        reason: 'Misleading Metadata or Thumbnail',
        details: 'Checking if thumbnail representation matches actual robot abilities demonstrated in footage.',
        status: 'Under Review',
        statusNote: 'Our Trust & Safety team is currently investigating this report against our Community Guidelines.',
        reportedAt: new Date(Date.now() - 3600000 * 6),
        resolvedAt: null
      }
    ];

    await Report.insertMany(sampleReports);
    console.log(`Inserted ${sampleReports.length} Historical Reports into MongoDB.`);

    console.log('MongoDB data seeded successfully with Multi-Category Ranked Global Showcase!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding data:', error);
    process.exit(1);
  }
};

seedData();
